version: "2"
services:
  app:
    build:
      context: .docker/nginx/
    image: vulpea/magento2-nginx
    container_name: sandbox-nginx
    depends_on:
      - db
      - phpfpm
    links:
      - db
      - phpfpm
      - redis
      - elasticsearch01
    volumes: &appvolumes
      - ./html:/var/www/html
      - ./.composer:/var/www/.composer
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
      - $HOME/.ssh/id_rsa:/var/www/.ssh/id_rsa
      - $HOME/.ssh/known_hosts:/var/www/.ssh/known_hosts
    ports:
      - 80
    networks:
      default:
        ipv4_address: 172.20.0.3
    environment:
      - XDEBUG_CONFIG=remote_host=172.20.0.1
      - PHP_IDE_CONFIG=serverName=sandbox.local
      - XDEBUG_CONFIG=xdebug.idekey=PHPSTORM

  phpfpm:
    build:
      context: .docker/php/
    image: vulpea/magento2-php
    container_name: sandbox-php
    depends_on:
      - db
    links:
      - db
      - elasticsearch01
    volumes: *appvolumes
    ports:
      - 9000
    networks:
      default:
        ipv4_address: 172.20.0.4
    env_file: .env/setup.env
    environment:
      - XDEBUG_CONFIG=remote_host=172.20.0.1
      - PHP_IDE_CONFIG=serverName=sandbox.local
      - XDEBUG_CONFIG=xdebug.idekey=PHPSTORM

  db:
    image: mysql:5.7
    container_name: sandbox-db
    volumes:
      - ./.docker/dbdata/mysql:/var/lib/mysql
    ports:
      - 3306
    networks:
      default:
        ipv4_address: 172.20.0.5
    env_file: .env/mysql.env

  setup:
    image: vulpea/magento2-php
    container_name: sandbox-setup
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes: *appvolumes
    env_file: .env/setup.env

  redis:
    image: redis:3.0.7
    container_name: vulpea_redis_session
    ports:
      - 6379
      - 1985
    networks:
      default:
        ipv4_address: 172.20.0.6

  mailcatcher:
     build: ./.docker/mailcatcher
     container_name: vulpea_mailcatcher_os
     image: vulpea/mailcatcher:0.6.4
     ports:
       - 1080
       - 1025
     networks:
       default:
         ipv4_address: 172.20.0.8

  elasticsearch1:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
      container_name: sandbox-elastic1
      environment:
        - node.name=elasticsearch1
        - cluster.name=magento-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./.docker/elasticsearch/elasticsearch1/data:/usr/share/elasticsearch/data
        - ./.docker/elasticsearch/elasticsearch1/logs:/usr/share/elasticsearch/logs
      ports:
        - 9200
      networks:
         default:
           ipv4_address: 172.20.0.9

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1


